import { company as c, formatDate } from './company.js'

export default {
  slug: 'privacy-policy',
  title: 'Privacy Policy',
  updated: formatDate(c.updatedISO, 'en-GB'),
  summary: `How ${c.name} collects, uses, stores, and protects your information when you use our website and services.`,
  intro: [
    {
      t: 'p',
      text: `This Privacy Policy describes how ${c.legalName} ("we", "us", or "our") collects, uses, stores, and protects your information when you visit ${c.url} (the "Website").`,
    },
    {
      t: 'p',
      text: 'By using the Website, you agree to the collection and use of information in accordance with this Privacy Policy. If you do not agree with any part of this policy, please discontinue use of the Website.',
    },
  ],
  sections: [
    {
      id: 'definitions',
      title: 'Interpretation and Definitions',
      blocks: [
        { t: 'p', text: 'For the purposes of this Privacy Policy:' },
        {
          t: 'dl',
          items: [
            ['Company', `refers to ${c.legalName}, located at ${c.address}.`],
            ['Website', `refers to ${c.url}.`],
            [
              'You',
              'refers to the individual accessing the Website, or the company or legal entity on whose behalf that individual is accessing the Website.',
            ],
            [
              'Personal Data',
              'means any information relating to an identified or identifiable individual.',
            ],
            [
              'Usage Data',
              'refers to data collected automatically, either generated by your use of the Website or from the Website infrastructure itself.',
            ],
            [
              'Cookies',
              'are small files placed on your device by a website, containing details of your browsing activity.',
            ],
            [
              'Service Provider',
              'means any third party that processes data on our behalf to help us operate the Website.',
            ],
          ],
        },
      ],
    },
    {
      id: 'information-we-collect',
      title: 'Information We Collect',
      blocks: [
        { t: 'h', text: 'Personal Data You Provide' },
        {
          t: 'p',
          text: 'We collect Personal Data only when you voluntarily submit it, for example through our contact form. This may include:',
        },
        {
          t: 'ul',
          items: [
            'Full name',
            'Email address',
            'Phone number',
            'Company name and job title',
            'The content of any message, project brief, or inquiry you send us',
          ],
        },
        {
          t: 'p',
          text: 'We do not require you to create an account, and we do not collect payment information through this Website.',
        },
        { t: 'h', text: 'Usage Data' },
        {
          t: 'p',
          text: 'Usage Data is collected automatically when you visit the Website. It may include:',
        },
        {
          t: 'ul',
          items: [
            "Your device's IP address and approximate location (city or country level)",
            'Browser type and version',
            'Operating system and device type',
            'Pages you visit, time spent on each page, and the order of pages viewed',
            'Referring website or search terms that brought you here',
            'Date and time of your visit',
          ],
        },
        {
          t: 'p',
          text: 'This data is collected in aggregate and is used to understand how visitors interact with our Website. It is not used to identify you personally.',
        },
        { t: 'h', text: 'Sensitive Information' },
        {
          t: 'p',
          text: 'We do not intentionally collect sensitive categories of information such as health data, biometric data, racial or ethnic origin, religious beliefs, or criminal records. Please do not include such information in messages you send us through the Website.',
        },
      ],
    },
    {
      id: 'cookies',
      title: 'Cookies and Tracking Technologies',
      blocks: [
        {
          t: 'p',
          text: 'We use cookies and similar tracking technologies to operate the Website and analyze how it is used.',
        },
        {
          t: 'table',
          head: ['Type', 'Purpose', 'Essential?'],
          rows: [
            [
              'Strictly necessary',
              'Enable core functions such as security, form submission, and load balancing',
              'Yes, cannot be disabled',
            ],
            [
              'Preference',
              'Remember your settings, such as language or display mode',
              'No',
            ],
            [
              'Analytics',
              'Measure visitor numbers, traffic sources, and page performance in aggregate',
              'No',
            ],
            [
              'Marketing',
              'Measure the effectiveness of campaigns and display relevant advertising',
              'No',
            ],
          ],
        },
        {
          t: 'p',
          text: '**Managing cookies.** Most browsers allow you to refuse or delete cookies through their settings. Disabling non-essential cookies will not prevent you from using the Website, though some features may not function as intended.',
        },
        {
          t: 'note',
          text: 'If you deploy a consent banner, add a line here pointing readers to the "Cookie Settings" link in the site footer.',
        },
      ],
    },
    {
      id: 'how-we-use',
      title: 'How We Use Your Information',
      blocks: [
        {
          t: 'p',
          text: 'We use the information we collect for the following purposes:',
        },
        {
          t: 'ol',
          items: [
            '**To respond to your inquiries**: to answer questions, prepare proposals, and follow up on contact form submissions.',
            '**To provide our services**: to communicate with you about projects, deliverables, and ongoing work.',
            '**To measure advertising campaigns**: to assess the effectiveness of our advertising through third-party advertising pixels, only where you have accepted marketing cookies.',
            '**To operate and improve the Website**: to analyze usage patterns and improve performance, layout, and content.',
            '**To maintain security**: to detect, prevent, and address spam, fraud, bot traffic, and technical issues.',
            '**To comply with legal obligations**: to meet accounting, tax, or regulatory requirements, or to respond to lawful requests from public authorities.',
          ],
        },
        {
          t: 'p',
          text: 'We will not use your information for purposes materially different from those described above without informing you first.',
        },
      ],
    },
    {
      id: 'legal-basis',
      title: 'Legal Basis for Processing',
      blocks: [
        {
          t: 'p',
          text: 'We process Personal Data on one or more of the following grounds:',
        },
        {
          t: 'dl',
          items: [
            [
              'Consent',
              'where you have explicitly agreed, such as by accepting non-essential cookies.',
            ],
            [
              'Contract',
              'where processing is necessary to enter into or perform an agreement with you.',
            ],
            [
              'Legal obligation',
              'where we are required to process data under applicable law.',
            ],
            [
              'Legitimate interests',
              'where processing is necessary for our reasonable business interests, such as securing the Website or understanding how it is used, provided those interests are not overridden by your rights.',
            ],
          ],
        },
        {
          t: 'p',
          text: 'Our processing is carried out in accordance with Indonesian Law No. 27 of 2022 on Personal Data Protection (UU PDP), and, where applicable, the EU General Data Protection Regulation (GDPR).',
        },
      ],
    },
    {
      id: 'sharing',
      title: 'Sharing and Disclosure of Information',
      blocks: [
        { t: 'lede', text: 'We do not sell your Personal Data.' },
        {
          t: 'p',
          text: 'We may share your information in the following limited circumstances:',
        },
        {
          t: 'ul',
          items: [
            `**With Service Providers** who help us operate the Website and our business: hosting and infrastructure ${c.processors.hosting}, analytics ${c.processors.analytics}, email platforms ${c.processors.email}, and advertising platforms ${c.processors.advertising}.`,
            '**For legal reasons**, where disclosure is required by law, court order, or a valid request from a government or law enforcement authority.',
            '**In a business transfer**, such as a merger, acquisition, or sale of assets, in which case we will notify you before your data becomes subject to a different privacy policy.',
            '**With your consent**, for any other purpose disclosed to you at the time.',
          ],
        },
        {
          t: 'p',
          text: 'All Service Providers are contractually required to process data only on our instructions and to apply appropriate safeguards.',
        },
      ],
    },
    {
      id: 'retention',
      title: 'Data Retention',
      blocks: [
        {
          t: 'p',
          text: 'We retain Personal Data only for as long as necessary to fulfill the purposes described in this policy, or as required by applicable law. As a general guide:',
        },
        {
          t: 'table',
          head: ['Category', 'Retention period'],
          rows: [
            [
              'Contact form submissions and inquiry records',
              `${c.retention.enquiries} from the last communication`,
            ],
            [
              'Business and accounting records',
              `${c.retention.accounting}, as required by tax and company-records regulations`,
            ],
            ['Server logs and analytics data', c.retention.logs],
          ],
        },
        {
          t: 'p',
          text: 'Once the retention period ends, data is permanently deleted or anonymized so it can no longer identify you.',
        },
      ],
    },
    {
      id: 'transfers',
      title: 'International Data Transfers',
      blocks: [
        {
          t: 'p',
          text: 'Some of our Service Providers operate servers outside Indonesia. Where your information is transferred internationally, we take reasonable steps to ensure the receiving country provides an adequate level of protection, or that appropriate contractual safeguards are in place, consistent with applicable data protection law.',
        },
      ],
    },
    {
      id: 'security',
      title: 'Data Security',
      blocks: [
        {
          t: 'p',
          text: 'We apply reasonable technical and organizational measures to protect your information, including:',
        },
        {
          t: 'ul',
          items: [
            'Encrypted data transmission via HTTPS/TLS',
            'Access controls limiting data access to authorized personnel only',
            'Regular software updates and security patching',
            'Routine backups and monitoring for unauthorized activity',
          ],
        },
        {
          t: 'p',
          text: 'However, no method of transmission over the internet or method of electronic storage is completely secure. While we strive to protect your Personal Data, we cannot guarantee absolute security.',
        },
        {
          t: 'p',
          text: '**Breach notification.** In the event of a personal data breach, we will notify affected individuals and the relevant supervisory authority within the timeframe required by applicable law.',
        },
      ],
    },
    {
      id: 'your-rights',
      title: 'Your Rights',
      blocks: [
        {
          t: 'p',
          text: 'Depending on your jurisdiction, you have the right to:',
        },
        {
          t: 'ol',
          items: [
            '**Be informed** about how your Personal Data is collected and used.',
            '**Access** the Personal Data we hold about you and request a copy.',
            '**Rectify** inaccurate or incomplete data.',
            '**Erase** your Personal Data, where we have no overriding legal obligation to retain it.',
            '**Withdraw consent** at any time, without affecting the lawfulness of processing carried out beforehand.',
            '**Object** to processing based on legitimate interests, including direct marketing.',
            '**Restrict** or suspend processing in certain circumstances.',
            '**Data portability**: receive your data in a structured, machine-readable format and transmit it to another controller.',
            '**Lodge a complaint** with the competent data protection authority.',
          ],
        },
        {
          t: 'p',
          text: `To exercise any of these rights, contact us at ${c.email}. We will respond within ${c.terms.responseTime}. We may ask you to verify your identity before fulfilling the request, in order to protect your data from unauthorized access.`,
        },
      ],
    },
    {
      id: 'children',
      title: "Children's Privacy",
      blocks: [
        {
          t: 'p',
          text: `The Website is not directed at children under the age of ${c.terms.minAge}, and we do not knowingly collect Personal Data from children. If you believe a child has provided us with Personal Data, please contact us at ${c.email} so we can remove it.`,
        },
      ],
    },
    {
      id: 'third-party-links',
      title: 'Links to Other Websites',
      blocks: [
        {
          t: 'p',
          text: 'Our Website may contain links to third-party websites, including client projects, social media profiles, and partner sites. This Privacy Policy does not apply to those sites. We have no control over and assume no responsibility for the content or privacy practices of any third party. We encourage you to review the privacy policy of every site you visit.',
        },
      ],
    },
    {
      id: 'changes',
      title: 'Changes to This Privacy Policy',
      blocks: [
        {
          t: 'p',
          text: 'We may update this Privacy Policy from time to time to reflect changes in our practices or legal requirements. The updated version will be posted on this page with a revised "Last updated" date. For material changes, we will provide a more prominent notice, such as an email notification or a banner on the Website.',
        },
        { t: 'p', text: 'We encourage you to review this page periodically.' },
      ],
    },
    {
      id: 'contact',
      title: 'Contact Us',
      blocks: [
        {
          t: 'p',
          text: 'If you have questions, concerns, or requests regarding this Privacy Policy or how we handle your information, please contact us:',
        },
        {
          t: 'contact',
          lines: [
            ['Company', c.legalName],
            ['Address', c.address],
            ['Email', c.email],
            ['Phone', c.phone],
            ['Website', c.url],
          ],
        },
      ],
    },
  ],
}
